### ISSUE TITLE
intel insrinsics guide xml

### ISSUE THREAD

**Issue by seanjensengrey** [akhin/microarchitecture-cheatsheet#2]
The data the powers the wonderful site is available as an xml file. It might be of interest.

https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#

https://www.intel.com/content/dam/develop/public/us/en/include/intrinsics-guide/data-3-6-3.xml

**Comment by akhin** [comment]
Thanks very much, was aware of the page though didn`t know that its data was available as well.

In the early versions I was using this page for the link for "Arithmetic Realm -> X86 Extensions -> List of extensions...". 
I think my justification to revert to a simpler Wikipedia link  were : avoiding more-cpp-welcoming  intrinsics , but I didn`t revisit it and now think it is pointless, as this site probably is the best one showcasing them. Definitely can use that link instead.

As for the data side, any recommendations to utilise it ?

Thanks,
Akin

**Comment by seanjensengrey** [comment]
I don't know of any alternate visualizations or viewers for the xml data, the page itself is wonderful.  I'd love to see the same thing for the RISC-V ecosystem.
