### ISSUE TITLE
dump all links into file

### ISSUE THREAD

**Issue by matu3ba** [akhin/microarchitecture-cheatsheet#3]
Having links stored in a file allows quicker lookup, for example via text browser. Also allows giving some more instructions to search the article in a wayback machine in case the website gets offline.

**Comment by akhin** [comment]
Thanks , I have added references.txt file .

**Comment by akhin** [comment]
So I hope you are ok to close the issue ?

Otherwise I can do further work on the text file if you have more suggestions.

Cheers,
Akin

**Comment by matu3ba** [comment]
Looking good now. Sorry for late response. Was on holiday with minimal internet access.
