### ISSUE TITLE
SRAM and DRAM backwards in another place

### ISSUE THREAD

**Issue by jminer** [akhin/microarchitecture-cheatsheet#4]
In issue #1, the RAM types were fixed in one place, but they are still backwards above. It currently says

> System memory is made of SRAM cells. Cache memory on the other hand are made of DRAM cells which is much faster than DRAMs.

but it should say

> System memory is made of DRAM cells. Cache memory on the other hand is made of SRAM cells which is much faster than DRAMs.

**Comment by akhin** [comment]
Thanks very much , just updated.

**Comment by jminer** [comment]
Thanks!
